name: Trigger auto deployment for container-app-3unbk45ggbvsu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-3unbk45ggbvsu-AutoDeployTrigger-8d09102a-5c24-4176-92b7-6d9590c893df.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP3UNBK45GGBVSU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP3UNBK45GGBVSU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP3UNBK45GGBVSU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP3UNBK45GGBVSU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP3UNBK45GGBVSU_REGISTRY_PASSWORD }}
          containerAppName: container-app-3unbk45ggbvsu
          resourceGroup: todonodejspgsqlgoogleauth8296be67
          imageToBuild: default/container-app-3unbk45ggbvsu:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


